# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'            # or whichever Node.js version you support
  displayName: 'Use Node.js'

- script: |
    npm ci                        # clean install based on lockfile
  displayName: 'Install dependencies'

- script: |
    npm run build                 # transpile / compile step
  displayName: 'Build'

- script: |
    npm test                      # if you have tests
  displayName: 'Run tests'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'dist'         # output folder from your build script
    artifactName: 'drop'
  displayName: 'Publish artifacts'

